const router=require('express').Router();
const protect=require('../middleware/auth.middleware');
const roleCheck=require('../middleware/roleCheck.middleware');
const service=require('../services/announcement.service');
const push=require('../services/push.service');
const {rateLimit}=require('express-rate-limit');
const wrap=fn=>async(req,res,next)=>{try{await fn(req,res)}catch(error){next(error)}};
const ict=roleCheck(['admin']),student=roleCheck(['student','admin','lecturer']);
const page=req=>Math.max(1,Math.min(10000,parseInt(req.query.page,10)||1));
router.use(protect);
router.use((req,res,next)=>{res.set('Cache-Control','private, no-store');next()});
router.get('/admin',ict,wrap(async(req,res)=>res.json({...await service.adminList(page(req),req.user,req.query.channel),pushConfigured:Boolean(push.configuration())})));
router.get('/staff-audiences',ict,wrap(async(req,res)=>res.json({data:[...await require('../models/admin.model').find({status:{$ne:'archived'}}).select('username adminType role'),...await require('../models/staff.model').find({status:'active',role:'lecturer'}).select('name role')]})));
router.get('/audiences',ict,wrap(async(req,res)=>res.json({faculties:await require('../models/faculty.model').find().select('name'),departments:await require('../models/department.model').find().select('name faculty')})));
router.post('/preview',ict,wrap(async(req,res)=>{const data=await service.fields(req.body);service.canPublish(data.channel,req.user);res.json({count:(await service.recipients(data)).length})}));
router.post('/',ict,wrap(async(req,res)=>res.status(201).json({data:await service.save(null,req.body,req.user)})));
router.put('/:id',ict,wrap(async(req,res)=>res.json({data:await service.save(req.params.id,req.body,req.user)})));
router.post('/:id/publish',ict,rateLimit({windowMs:60000,limit:10,keyGenerator:req=>req.user.userId,standardHeaders:true,legacyHeaders:false}),wrap(async(req,res)=>res.json({data:await service.publish(req.params.id,req.user)})));
router.post('/:id/withdraw',ict,wrap(async(req,res)=>res.json({data:await service.withdraw(req.params.id,req.user)})));
router.get('/inbox',student,wrap(async(req,res)=>res.json(await service.studentList(req.user.userId,page(req),req.user.role))));
router.get('/push/config',student,(req,res)=>res.json({enabled:Boolean(push.configuration()),publicKey:push.configuration()?.publicKey||null}));
router.post('/push/subscribe',student,wrap(async(req,res)=>res.json(await push.subscribe(req.body,req.user))));
router.post('/push/unsubscribe',student,wrap(async(req,res)=>res.json(await push.unsubscribe(req.body.endpoint,req.user))));
router.post('/:id/read',student,wrap(async(req,res)=>res.json({data:await service.read(req.params.id,req.user.userId,req.user.role)})));
module.exports=router;
