const router=require('express').Router(),Assessment=require('../models/assessment.model'),Attendance=require('../models/assessmentAttendance.model'),Sheet=require('../models/scoreSheet.model'),Course=require('../models/timetableCourse.model');
const service=require('../services/assessment.service'),scores=require('../services/scoreSheet.service'),biometric=require('../services/biometric.service'),AppError=require('../utils/appError');
const roles=require('../middleware/roleCheck.middleware'),academic=roles(['admin'],['timetable_admin']),invigilator=roles(['invigilator']),lecturer=roles(['lecturer']);
const mixed=list=>(req,res,next)=>req.user.role==='admin'?academic(req,res,next):roles(list.filter(r=>r!=='admin'))(req,res,next);
const wrap=fn=>async(req,res,next)=>{try{await fn(req,res)}catch(e){next(e)}};
router.use(require('../middleware/auth.middleware'));router.use((req,res,next)=>{res.set('Cache-Control','private, no-store');next()});
router.get('/student',roles(['student']),wrap(async(req,res)=>res.json({data:await Assessment.find({'roster.student':req.user.userId,state:{$ne:'cancelled'}}).select('courseCode courseName session semester kind startAt endAt venue state').sort({startAt:-1}).limit(500)})));
router.get('/courses',mixed(['admin','lecturer']),wrap(async(req,res)=>{const query=req.user.role==='lecturer'?{lecturerId:req.user.userId}:{};if(req.query.session)query.session=req.query.session;if(req.query.semester)query.semester=req.query.semester;res.json({data:await Course.find(query).sort({session:-1,courseCode:1})})}));
router.get('/scanner',invigilator,(req,res)=>res.json(biometric.status()));
router.post('/preview',academic,wrap(async(req,res)=>res.json(await service.preview(req.body))));
router.post('/publish',academic,wrap(async(req,res)=>res.status(201).json({data:await service.publish(req.body.entries,req.user)})));
router.get('/',mixed(['admin','lecturer','invigilator']),wrap(async(req,res)=>{
 const query={};if(req.user.role==='lecturer'){const courses=await Course.find({lecturerId:req.user.userId}).select('_id');query.course={$in:courses.map(c=>c._id)}}if(req.user.role==='invigilator')query.state='published';
 const data=await Assessment.find(query).select('-roster').sort({startAt:-1}).limit(500);res.json({data:data.map(a=>({...a.toObject(),checkInOpen:service.isOpen(a)}))});
}));
router.get('/sheets/:courseId',mixed(['admin','lecturer']),wrap(async(req,res)=>{await scores.access(req.params.courseId,req.user);res.json({data:await Sheet.findOne({course:req.params.courseId})})}));
router.post('/sheets/:courseId/prepare',mixed(['admin','lecturer']),wrap(async(req,res)=>res.json({data:await scores.prepare(req.params.courseId,req.user)})));
router.put('/sheets/:courseId',lecturer,wrap(async(req,res)=>res.json({data:await scores.save(req.params.courseId,req.body,req.user)})));
router.post('/sheets/:courseId/submit',lecturer,wrap(async(req,res)=>res.json({data:await scores.save(req.params.courseId,req.body,req.user,true)})));
router.post('/sheets/:courseId/release',academic,wrap(async(req,res)=>res.json({data:await scores.release(req.params.courseId,req.user)})));
router.post('/sheets/:courseId/correct',academic,wrap(async(req,res)=>res.json({data:await scores.correct(req.params.courseId,req.body,req.user)})));
router.post('/exceptions/:id/approve',academic,wrap(async(req,res)=>res.json({data:await service.approveException(req.params.id,req.body.reason,req.user)})));
router.post('/exceptions/:id/reject',academic,wrap(async(req,res)=>res.json({data:await service.approveException(req.params.id,req.body.reason,req.user,false)})));
router.post('/:id/state',academic,wrap(async(req,res)=>res.json({data:await service.transition(req.params.id,req.body.action,req.user)})));
router.post('/:id/exception',invigilator,wrap(async(req,res)=>res.status(201).json({data:await service.exception(req.params.id,req.body,req.user)})));
router.post('/:id/scan',invigilator,wrap(async(req,res)=>{const a=await Assessment.findById(req.params.id);if(!a||!service.isOpen(a))throw new AppError('Check-in is not open',409);res.json(await biometric.verify())}));
router.get('/:id',mixed(['admin','lecturer','invigilator']),wrap(async(req,res)=>{
 const a=await Assessment.findById(req.params.id);if(!a)throw new AppError('Assessment not found',404);
 if(req.user.role==='lecturer')await scores.access(a.course,req.user);
 if(req.user.role==='invigilator'&&!service.isOpen(a))throw new AppError('This assessment is not open for check-in',409);
 res.json({data:a,attendance:await Attendance.find({assessment:a.id}).sort({createdAt:-1}),checkInOpen:service.isOpen(a)});
}));
module.exports=router;
