const router=require('express').Router(),mongoose=require('mongoose'),crypto=require('node:crypto'),sharp=require('sharp'),multer=require('multer');
const {FeedPost:Post,FeedComment:Comment,FeedLike:Like}=require('../models/feed.model');
const Student=require('../models/student.model'),Admin=require('../models/admin.model'),Staff=require('../models/staff.model'),Announcement=require('../models/announcement.model'),Receipt=require('../models/announcementReceipt.model'),Subscription=require('../models/pushSubscription.model'),Delivery=require('../models/pushDelivery.model'),Audit=require('../models/auditLog.model');
const AppError=require('../utils/appError'),roles=require('../middleware/roleCheck.middleware');
const mediaStorage=require('../services/mediaStorage.service');
const wrap=fn=>async(req,res,next)=>{try{await fn(req,res)}catch(e){next(e)}};
const actor=req=>({author:req.user.userId,authorRole:req.user.role,authorName:req.account.name||req.account.username});
const moderator=req=>req.user.role==='admin';
const canPost=req=>moderator(req)||req.user.role==='student'&&req.account.canPostFeed===true;
const page=req=>Math.max(1,Math.min(10000,parseInt(req.query.page)||1));
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024,files:4,fields:1},fileFilter:(req,file,cb)=>cb(['image/jpeg','image/png','image/webp'].includes(file.mimetype)?null:new AppError('Only JPEG, PNG and WebP pictures are accepted; no videos or animations',400),true)}).array('images',4);
router.use(require('../middleware/auth.middleware'),roles(['student','admin','lecturer']));
router.use((req,res,next)=>{res.set('Cache-Control','private, no-store');next()});
router.get('/permissions',(req,res)=>res.json({canPost:canPost(req),canModerate:moderator(req)}));
router.get('/unread',wrap(async(req,res)=>{const notices=await Announcement.find({channel:'feed',state:'published'}).select('_id');res.json({unread:await Receipt.countDocuments({student:req.user.userId,readAt:null,announcement:{$in:notices.map(n=>n._id)}})})}));
router.get('/publishers',roles(['admin'],['student_officer']),wrap(async(req,res)=>res.json({data:await Student.find({canPostFeed:true,status:{$nin:['archived','graduated']}}).select('name matricNumber department level canPostFeed')})));
router.put('/publishers/:id',roles(['admin'],['student_officer']),wrap(async(req,res)=>{
 if(typeof req.body.allowed!=='boolean')throw new AppError('Choose whether posting is allowed',400);
 const student=await Student.findOneAndUpdate({_id:req.params.id,status:{$nin:['archived','graduated']}},{$set:{canPostFeed:req.body.allowed}},{new:true});if(!student)throw new AppError('Active student not found',404);
 await Audit.create({performedBy:req.user.userId,adminType:req.user.adminType,action:'UPDATE',targetType:'FEED',affectedStudent:student.id,description:`SRC posting permission ${req.body.allowed?'granted':'removed'}`});res.json({data:{_id:student.id,name:student.name,canPostFeed:student.canPostFeed}});
}));
router.get('/images/:filename',wrap(async(req,res)=>{if(!/^(?:cld_)?[a-f0-9]{32}\.webp$/.test(req.params.filename)||!await Post.exists({images:req.params.filename,deletedAt:null}))throw new AppError('Image not found',404);res.set('Cache-Control','private, no-store').type('webp').send(await mediaStorage.read('feed',req.params.filename))}));
async function decorate(posts,account){const ids=posts.map(p=>p._id);const [likes,comments,mine]=await Promise.all([Like.aggregate([{$match:{post:{$in:ids}}},{$group:{_id:'$post',count:{$sum:1}}}]),Comment.aggregate([{$match:{post:{$in:ids},deletedAt:null}},{$group:{_id:'$post',count:{$sum:1}}}]),Like.find({post:{$in:ids},account}).select('post')]);return posts.map(p=>({...p,likeCount:likes.find(l=>String(l._id)===String(p._id))?.count||0,commentCount:comments.find(l=>String(l._id)===String(p._id))?.count||0,liked:mine.some(l=>String(l.post)===String(p._id))}))}
router.get('/',wrap(async(req,res)=>{const p=page(req),filter={deletedAt:null};const data=await Post.find(filter).sort({createdAt:-1,_id:-1}).skip((p-1)*20).limit(20).lean();await Receipt.updateMany({student:req.user.userId,announcement:{$in:data.map(p=>p.notification)}},{$set:{readAt:new Date()}});res.json({data:await decorate(data,req.user.userId),page:p,total:await Post.countDocuments(filter)})}));
router.post('/',(req,res,next)=>canPost(req)?next():next(new AppError('Posting is reserved for admins and SRC students selected by the student officer',403)),require('express-rate-limit').rateLimit({windowMs:3600000,limit:10,keyGenerator:req=>req.user.userId,standardHeaders:true,legacyHeaders:false}),upload,wrap(async(req,res)=>{
 const body=String(req.body.body||'').trim();if(body.length>5000||!body&&!req.files?.length)throw new AppError('Write a post or add a picture (maximum 5000 characters)',400);
 const files=[];let saved=false;const session=await mongoose.startSession();let doc;
 try{const useCloudinary=mediaStorage.validateCloudinary();for(const file of req.files||[]){const name=`${useCloudinary?'cld_':''}${crypto.randomBytes(16).toString('hex')}.webp`;const image=sharp(file.buffer,{limitInputPixels:30000000});let normalized;try{const metadata=await image.metadata();if(!['jpeg','png','webp'].includes(metadata.format)||metadata.pages>1)throw new Error();normalized=await image.rotate().resize({width:1600,height:1600,fit:'inside',withoutEnlargement:true}).webp({quality:85}).toBuffer()}catch{throw new AppError('Upload a valid, non-animated JPEG, PNG or WebP picture',400)}try{await mediaStorage.store(normalized,'feed',name)}catch{throw new AppError('Image storage is temporarily unavailable; please try again',503)}files.push(name)}
 await session.withTransaction(async()=>{
 // Recheck SRC permission at publication, after image processing.
 if(req.user.role==='student'&&!await Student.exists({_id:req.user.userId,canPostFeed:true,status:'active'}).session(session))throw new AppError('Your posting permission was removed',403);
 [doc]=await Post.create([{...actor(req),body,images:files}],{session});
 const [notice]=await Announcement.create([{title:'New campus feed post',body:'A new post is available in the campus feed.',channel:'feed',feedPost:doc.id,createdBy:req.user.userId,state:'published',publishedAt:new Date(),audience:{kind:'all',label:'Campus community'}}],{session});
 const recipients=[...await Student.find({status:{$nin:['archived','graduated']}}).select('_id role tokenVersion').session(session),...await Admin.find({status:{$ne:'archived'}}).select('_id role tokenVersion').session(session),...await Staff.find({status:'active',role:'lecturer'}).select('_id role tokenVersion').session(session)];
 notice.recipientCount=recipients.length;await notice.save({session});doc.notification=notice.id;await doc.save({session});
 if(recipients.length)await Receipt.insertMany(recipients.map(r=>({announcement:notice.id,student:r.id,recipientRole:r.role})),{session});
 const versions=new Map(recipients.map(r=>[r.id,r.tokenVersion||0]));const subs=await Subscription.find({student:{$in:recipients.map(r=>r.id)},active:true}).session(session);const jobs=subs.filter(s=>versions.get(String(s.student))===s.tokenVersion).map(s=>({announcement:notice.id,subscription:s.id,student:s.student,recipientRole:s.recipientRole}));if(jobs.length)await Delivery.insertMany(jobs,{session});
 });saved=true;res.status(201).json({data:doc});
 }finally{await session.endSession();if(!saved)await Promise.all(files.map(name=>mediaStorage.remove('feed',name).catch(()=>{})))}
}));
router.get('/:id',wrap(async(req,res)=>{const doc=await Post.findOne({_id:req.params.id,deletedAt:null}).lean();if(!doc)throw new AppError('Post unavailable',404);if(doc.notification)await Receipt.updateOne({announcement:doc.notification,student:req.user.userId},{$set:{readAt:new Date()}});res.json({data:(await decorate([doc],req.user.userId))[0]})}));
router.delete('/:id',wrap(async(req,res)=>{
 const session=await mongoose.startSession();try{await session.withTransaction(async()=>{const doc=await Post.findOne({_id:req.params.id,deletedAt:null}).session(session);if(!doc)throw new AppError('Post unavailable',404);if(!moderator(req)&&String(doc.author)!==req.user.userId)throw new AppError('Only the author or an administrator can remove this post',403);doc.deletedAt=new Date();await doc.save({session});await Announcement.updateOne({_id:doc.notification},{$set:{state:'withdrawn',withdrawnAt:new Date()}},{session});await Delivery.updateMany({announcement:doc.notification,state:{$in:['pending','processing']}},{$set:{state:'skipped',leaseUntil:null}},{session});await Audit.create([{performedBy:req.user.userId,adminType:req.user.adminType,action:'DELETE',targetType:'FEED',targetId:doc.id,description:'Campus post removed; pending notifications cancelled'}],{session})});res.json({removed:true})}finally{await session.endSession()}
}));
router.put('/:id/like',wrap(async(req,res)=>{if(typeof req.body.liked!=='boolean')throw new AppError('Invalid like choice',400);if(!await Post.exists({_id:req.params.id,deletedAt:null}))throw new AppError('Post unavailable',404);if(req.body.liked){try{await Like.updateOne({post:req.params.id,account:req.user.userId},{$setOnInsert:{post:req.params.id,account:req.user.userId}},{upsert:true})}catch(e){if(e.code!==11000)throw e}}else await Like.deleteOne({post:req.params.id,account:req.user.userId});res.json({liked:req.body.liked,count:await Like.countDocuments({post:req.params.id})})}));
router.get('/:id/comments',wrap(async(req,res)=>{if(!await Post.exists({_id:req.params.id,deletedAt:null}))throw new AppError('Post unavailable',404);const p=page(req),filter={post:req.params.id,deletedAt:null};res.json({data:await Comment.find(filter).sort({createdAt:1}).skip((p-1)*30).limit(30),page:p,total:await Comment.countDocuments(filter)})}));
router.post('/:id/comments',require('express-rate-limit').rateLimit({windowMs:60000,limit:15,keyGenerator:req=>req.user.userId}),wrap(async(req,res)=>{const body=String(req.body.body||'').trim();if(!body||body.length>3000)throw new AppError('Comment must contain 1–3000 characters',400);if(!await Post.exists({_id:req.params.id,deletedAt:null}))throw new AppError('Post unavailable',404);res.status(201).json({data:await Comment.create({...actor(req),post:req.params.id,body})})}));
router.delete('/:post/comments/:id',wrap(async(req,res)=>{const doc=await Comment.findOne({_id:req.params.id,post:req.params.post,deletedAt:null});if(!doc)throw new AppError('Comment unavailable',404);if(!moderator(req)&&String(doc.author)!==req.user.userId)throw new AppError('You cannot remove this comment',403);doc.deletedAt=new Date();await doc.save();res.json({removed:true})}));
module.exports=router;
